name: build analyze, scan todo application
on:
  push:
    branches:
      - main
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Run SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=todo 
          -Dsonar.organization=CloudKubeSec
          -Dsonar.projectName=todo 
          


    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
    - run: npm install
    - run: npm test