name: build analyze, scan todo application
on:
  push:
    branches:
      - main
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4